---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: OCP Console
    url: 'https://console-openshift-console.{openshift_cluster_ingress_domain}'

  - name: Argo CD
    url: 'https://openshift-gitops-server-openshift-gitops.{openshift_cluster_ingress_domain}'

  - name: Developer Hub
    url: 'https://backstage-developer-hub-rhdh.{openshift_cluster_ingress_domain}'

  - name: Vault
    url: 'https://vault-vault.{openshift_cluster_ingress_domain}'

  - name: Keycloak
    url: 'https://sso.{openshift_cluster_ingress_domain}'

  - name: GitLab
    url: 'https://gitlab-gitlab.{openshift_cluster_ingress_domain}'

  - name: Terminal
    path: /wetty
    port: 443
