---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'

  - name: Argo CD
    url: 'https://openshift-gitops-server-openshift-gitops.${DOMAIN}'

  - name: Developer Hub
    url: 'https://backstage-developer-hub-rhdh.${DOMAIN}'

  - name: Vault
    url: 'https://vault-vault.${DOMAIN}'

  - name: Keycloak
    url: 'https://sso.${DOMAIN}'

  - name: GitLab
    url: 'https://gitlab-gitlab.${DOMAIN}'

  - name: Terminal
    path: /wetty
    port: 443
